//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_user_info
    {
        public System.Guid guid { get; set; }
        public string email { get; set; }
        public string name { get; set; }
        public Nullable<int> company_seq { get; set; }
        public string password { get; set; }
        public string company_nm { get; set; }
    }
}
